name: Build Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_push_el7:
    runs-on: ubuntu-latest
    env:
      CHINA_MIRROR: "0"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build and push CentOS 7
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile.centos
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:centos7
            ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:el7
          build-args: |
            VERSION_NUM=7

      - name: Log out from Docker Hub
        run: docker logout

  build_and_push_el6:
    runs-on: ubuntu-latest
    env:
      CHINA_MIRROR: "0"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build and push CentOS 6
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile.centos
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:centos6
            ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:el6
          build-args: |
            VERSION_NUM=6

      - name: Log out from Docker Hub
        run: docker logout
